global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rabbitmq_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Your async-battle application
  - job_name: 'async-battle'
    static_configs:
      - targets: ['consumer:2112']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s 